name: Test build latex pdf
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
  push:
    branches: 
      - 'dev'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build pdf
      uses: xu-cheng/latex-action@v2
      with:
        root_file: latex/main.tex
      env:
        TEXINPUTS: ".:./latex//:"
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10 #install the python needed
    - name: Make report # run the run.py to get the latest data
      run: ./makeReport/run.sh
