name: Test build latex pdf
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
  push:
    branches: 
      - 'dev'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build pdf
      uses: xu-cheng/latex-action@v2
      with:
        root_file: latex/main.tex
      env:
        TEXINPUTS: ".:./latex//:"
